language: python

os: linux
dist: xenial

python:
    # - "2.7" # drop support for Python 2.7
    - "3.5"
    - "3.6"
    - "3.8"

before_install:
    - python --version
    - pip install -U pip
    - pip install nose
    - pip install -r requirements.txt

install:
    - pip install .

script:
    - cd tests
    - python -m nose
