name: Sphinx docs as gh-pages

on:
  push:
    tags:
      - doc/*

jobs:
  build:
    name: Build Sphinx Docs
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          persist-credentials: false

      - name: Set up Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Build docs
        run: |
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
          pip install sphinx sphinx_rtd_theme numpydoc
          cd docs
          export PYTHONPATH=../
          make html
      - name: Upload page artifacts
        uses: actions/upload-pages-artifact@v3
        with:
          path: docs/_build/html

  deploy:
    needs: build

    permissions:
      pages: write
      id-token: write

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    runs-on: ubuntu-latest
    steps:
      - name: Deploy Doxygen docs
        id: deployment
        uses: actions/deploy-pages@v4
